//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LieposNaujazodziai.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LieposNaujazodziai.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///
        ///&lt;!DOCTYPE rdf:RDF [
        ///    &lt;!ENTITY lmf &quot;http://www.lexinfo.net/lmf#&quot; &gt;
        ///    &lt;!ENTITY owl &quot;http://www.w3.org/2002/07/owl#&quot; &gt;
        ///    &lt;!ENTITY swrl &quot;http://www.w3.org/2003/11/swrl#&quot; &gt;
        ///    &lt;!ENTITY j.1 &quot;http://www.rastija.lt/isteklius#&quot; &gt;
        ///    &lt;!ENTITY swrlb &quot;http://www.w3.org/2003/11/swrlb#&quot; &gt;
        ///    &lt;!ENTITY xsd &quot;http://www.w3.org/2001/XMLSchema#&quot; &gt;
        ///    &lt;!ENTITY owl2xml &quot;http://www.w3.org/2006/12/owl2-xml#&quot; &gt;
        ///    &lt;!ENTITY rdfs &quot;http://www.w3.org/2000/01/rdf-schema#&quot; &gt;
        ///    &lt;!ENTITY rd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OWL_beginning {
            get {
                return ResourceManager.GetString("OWL_beginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- 
        ///    ///////////////////////////////////////////////////////////////////////////////////////
        ///    //
        ///    // Annotations
        ///    //
        ///    ///////////////////////////////////////////////////////////////////////////////////////
        ///     --&gt;
        ///
        ///
        ///
        ///    &lt;rdf:Description rdf:about=&quot;&amp;j.1;Resource.tartuvas&quot;&gt;
        ///        &lt;rdfs:label&gt;Lietuvių kalbos naujažodžių tartuvas&lt;/rdfs:label&gt;
        ///    &lt;/rdf:Description&gt;
        ///&lt;/rdf:RDF&gt;.
        /// </summary>
        internal static string OWL_ending {
            get {
                return ResourceManager.GetString("OWL_ending", resourceCulture);
            }
        }
    }
}
